seed: 314159

dataset:
    train_label_file: "./Bochum.json"
    test_label_file: "./Bremen.json"

dataloaders:
    worker_per_cpu: true
    num_workers: 1
    batch_size: 4

model:
    learning_rate: 0.02
    iou_threshold: 0.5
    num_of_classes: 8
    trainable_backbone_layers: 3
    early_stopping_patience: 3
    early_stopping_min_delta: 0.0001

trainer:                                 
    root_dir: "models"
    max_epochs: 20
    tune: false
    limit_train_set: 1.0
    limit_valid_set: 1.0
    limit_test_set: 1.0
    fast_dev_run: false
    deterministic_trainer: false
