channels:
  - pytorch
  - conda-forge

dependencies:
  - black
  - flake8
  - ipython
  - jupyter
  - matplotlib=3.5.*
  - notebook
  - numpy=1.21.*
  - opencv=4.5.*
  - pandas=1.3.*
  - pillow=8.4.*
  - pip
  - pytest=6.2.*
  - python=3.9
  - pytorch=1.10.*
  - pyyaml=6.0
  - scikit-learn=1.0.*
  - setuptools=59.5.0
  - torchaudio=0.10.*
  - torchvision=0.11.*
  - pip:
    - albumentations==1.1.*
    - duplicate-finder
    - kaggle==1.5.*
    - pytorch-lightning==1.5.*
    - tensorboard
